create table if not exists public.rsvp_responses (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  attend boolean not null default true,
  guests integer not null default 1 check (guests between 0 and 10),
  note text,
  created_at timestamptz not null default now()
);

alter table public.rsvp_responses enable row level security;

grant insert, select on public.rsvp_responses to anon;
grant usage, select on sequence public.rsvp_responses_id_seq to anon;

drop policy if exists "Anyone can create RSVP responses" on public.rsvp_responses;
create policy "Anyone can create RSVP responses"
on public.rsvp_responses
for insert
to anon
with check (true);

-- Enable this only if responses.html should read responses directly in the browser.
-- Anyone with the anon key and the page URL can read the table when this is enabled.
drop policy if exists "Anyone can read RSVP responses" on public.rsvp_responses;
create policy "Anyone can read RSVP responses"
on public.rsvp_responses
for select
to anon
using (true);
